# Kernel SVM

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("Iris.csv")

In [3]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [5]:
df.shape

(150, 6)

In [6]:
x=df.drop("Species", axis=1)
y=df['Species']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)


In [11]:
from sklearn.svm import SVC
kernelsvm=SVC(kernel='poly')
kernelsvm.fit(x_train,y_train)
ypred=kernelsvm.predict(x_test)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix, matthews_corrcoef
print(confusion_matrix(y_test,ypred))
print(classification_report(y_test,ypred))
print(matthews_corrcoef(y_test,ypred))

[[ 5  0  5]
 [ 0  0 17]
 [ 0  6  5]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      0.50      0.67        10
Iris-versicolor       0.00      0.00      0.00        17
 Iris-virginica       0.19      0.45      0.26        11

       accuracy                           0.26        38
      macro avg       0.40      0.32      0.31        38
   weighted avg       0.32      0.26      0.25        38

-0.08828497095261659


# Gaussian Kernel 

In [17]:
from sklearn.svm import SVC
kernelsvm=SVC(kernel='rbf')
kernelsvm.fit(x_train,y_train)
ypred=kernelsvm.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix, matthews_corrcoef
print(confusion_matrix(y_test,ypred))
print(classification_report(y_test,ypred))
print(matthews_corrcoef(y_test, ypred))

[[10  0  0]
 [ 2 14  1]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       0.83      1.00      0.91        10
Iris-versicolor       1.00      0.82      0.90        17
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.92        38
      macro avg       0.92      0.94      0.92        38
   weighted avg       0.93      0.92      0.92        38

0.8870952043038726


# Sigmoid Kernel

In [18]:
from sklearn.svm import SVC
kernelsvm=SVC(kernel='sigmoid')
kernelsvm.fit(x_train,y_train)
ypred=kernelsvm.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix, matthews_corrcoef
print(confusion_matrix(y_test,ypred))
print(classification_report(y_test,ypred))
print(matthews_corrcoef(y_test,ypred))

[[ 5  0  5]
 [ 0  0 17]
 [ 0  6  5]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      0.50      0.67        10
Iris-versicolor       0.00      0.00      0.00        17
 Iris-virginica       0.19      0.45      0.26        11

       accuracy                           0.26        38
      macro avg       0.40      0.32      0.31        38
   weighted avg       0.32      0.26      0.25        38

-0.08828497095261659
